base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social.urls', namespace='social')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
# Url for social app
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name = 'social'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile/', views.profile, name='profile'),
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', views.log_out, name='logout'),
    path('register/', views.register, name='register'),
    path('user/edit', views.edit_user, name='edit_user'),
    path('ticket/', views.ticket, name='ticket'),
    path("password-change/", auth_view.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path("password-change/done", auth_view.PasswordChangeDoneView.as_view(), name="password_change_done"),
    path("password-reset/", auth_view.PasswordResetView.as_view(success_url="done"), name="password_reset"),
    path("password-reset/done", auth_view.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path("password-reset/<uidb64>/<token>/",
         auth_view.PasswordResetConfirmView.as_view(success_url="/password-reset/complete"),
         name="password_reset_confirm"
    ),
    path("password-reset/complete/", auth_view.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("posts/", views.post_list, name='post_list'),
    path("posts/<slug:tag_slug>", views.post_list, name='post_list_by_tag'),
    path("posts/detail/<pk>", views.post_detail, name='post_detail'),
    path("create_post/", views.create_post, name='create_post'),
    path("search/", views.post_search, name='post_search'),
    path("liked_post/", views.like_post, name='like_post'),
    path("save_post/", views.save_post, name='save_post'),
    path("user/", views.user_list, name='user_list'),
    path("user/<username>", views.user_detail, name='user_detail'),
    path("follow/", views.user_follow, name='user_follow'),
]

social/models.py
from django.urls import reverse

from django.db import models
from django.contrib.auth.models import AbstractUser
from taggit.managers import TaggableManager


class User(AbstractUser):
    # Custom user model
    date_of_birth = models.DateField(null=True, blank=True, verbose_name="تاریخ تولد")
    bio = models.TextField(max_length=120, null=True, blank=True, verbose_name="بایو")
    photo = models.ImageField(upload_to="account_images/", null=True, blank=True, verbose_name="تصویر")
    job = models.CharField(max_length=120, null=True, blank=True, verbose_name="شغل")
    phone = models.CharField(max_length=11, verbose_name="موبایل")
    following = models.ManyToManyField('self', through='Contact', related_name='followers', symmetrical=False)

    def get_absolute_url(self):
        return reverse("social:user_detail", args=[self.username])


class Post(models.Model):
    # User posts model
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author', verbose_name='نویسنده')
    description = models.TextField(verbose_name='متن')
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    likes = models.ManyToManyField(User, related_name="liked_post", blank=True)
    saved_by = models.ManyToManyField(User, related_name="saved_posts", blank=True)
    total_likes = models.PositiveIntegerField(default=0)
    tags = TaggableManager()

    class Meta:
        ordering = ['-create']
        indexes = [
            models.Index(fields=['-create']),
            models.Index(fields=['-total_likes']),
        ]
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.author.first_name

    def get_absolute_url(self):
        return reverse('social:post_detail', args={self.id})


class Contact(models.Model):
    # Custom M2M Field
    user_from = models.ForeignKey(User, related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey(User, related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=['-created']),
        ]
        ordering = ['-created']

    def __str__(self):
        return f'{self.user_from} following {self.user_to}'

social/forms.py
# Forms for social app
from django import forms
from django.core.exceptions import ValidationError

from .models import *


class UserRegistrationForm(forms.ModelForm):
    # Registration form
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=50, widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'phone']

    def clean_password2(self):
        # Checked password and re-password is equal
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise ValidationError("رمزعبور یکسان نمیباشد")
        return cd['password2']

    def clean_username(self):
        # Checked not exists username
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise ValidationError("نام کاربری از قبل وجود دارد")
        return username

    def clean_phone(self):
        # Checked not exists phone number
        phone = self.cleaned_data['phone']
        if User.objects.filter(phone=phone).exists():
            raise ValidationError("شماره موبایل از قبل وجود دارد")
        return phone


class UserEditForm(forms.ModelForm):
    # Edit user information form
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'date_of_birth', 'photo', 'email', 'phone']

    def clean_username(self):
        # Checked not exists username
        username = self.cleaned_data['username']
        if User.objects.exclude(id=self.instance.id).filter(username=username).exists():
            raise ValidationError("نام کاربری از قبل وجود دارد")
        return username

    def clean_phone(self):
        # Checked not exists phone number
        phone = self.cleaned_data['phone']
        if User.objects.exclude(id=self.instance.id).filter(phone=phone).exists():
            raise ValidationError("شماره موبایل از قبل وجود دارد")
        return phone


class TicketForm(forms.Form):
    # form for send ticket
    CHOICES_SUBJECT = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش')
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=120, required=True)
    email = forms.EmailField(required=True)
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=CHOICES_SUBJECT, required=True)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError('شماره تلفن باید عدد باشد')
            else:
                return phone


class CreatePostForm(forms.ModelForm):
    # form for create post
    class Meta:
        model = Post
        fields = ['description', 'tags']


class SearchForm(forms.Form):
    query = forms.CharField()

social/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.http.response import HttpResponse
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from taggit.models import Tag
from django.db.models import Count, Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from social.forms import (
    UserRegistrationForm,
    UserEditForm,
    TicketForm,
    CreatePostForm,
    SearchForm
)
from social.models import Post, User, Contact


def index(request):
    return HttpResponse("شما با موفقیت وارد شدید")

def profile(request):
    user = User.objects.prefetch_related('followers', 'following').get(id=request.user.id)
    saved_posts = user.saved_posts.all()
    return render(request, 'social/profile.html', {'saved_posts': saved_posts, 'user': user})

def log_out(request):
    logout(request)
    return HttpResponse("شما خارج شدید")

def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required
def edit_user(request):
    if request.method == "POST":
        user_form = UserEditForm(data=request.POST, instance=request.user, files=request.FILES)
        if user_form.is_valid():
            user_form.save()
            return redirect('social:index')
    else:
        user_form = UserEditForm(instance=request.user)
    return render(request, 'registration/edit_user.html', {'user_form': user_form})

def ticket(request):
    # view for send ticket to mail
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            message = f"{cd['name']}\n{cd['email']}\n{cd['phone']}\n\n{cd['message']}"
            send_mail(
                cd['subject'],
                message, settings.EMAIL_HOST_USER,
                ['djangotestmenow@gmail.com'],
                fail_silently=False
            )
            messages.success(request, 'تیکت شما با موفقیت ارسال شد')
    else:
        form = TicketForm()
    return render(request, 'forms/ticket.html', {"form": form})

def post_list(request, tag_slug=None):
    # view for show list posts
    posts = Post.objects.select_related('author').order_by('-total_likes')
    tag = None
    if tag_slug:
        tag = Tag.objects.get(slug=tag_slug)
        posts = Post.objects.filter(tags__in=[tag])
    page = request.GET.get('page')
    paginator = Paginator(posts, 2)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = []
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return render(request, 'social/list_ajax.html', {"posts": posts})
    context = {
        'posts': posts,
        'tag': tag,
    }
    return render(request, 'social/list.html', context)

@login_required
def create_post(request):
    # view for create post form
    if request.method == "POST":
        form = CreatePostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            form.save_m2m()
            return redirect('social:post_list')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create_post.html', {"form": form})

def post_detail(request, pk):
    # show detail post and similar posts
    post = get_object_or_404(Post, id=pk)
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_post = Post.objects.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_post = similar_post.annotate(same_tags=Count('tags')).order_by('-same_tags')[:2]
    context = {
        'post': post,
        'similar_post': similar_post,
    }
    return render(request, 'social/detail.html', context)

def post_search(request):
    # view for search posts
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.filter(Q(tags__name__icontains=query) | Q(description__icontains=query))
    context = {
        'query': query,
        'results': results,
    }
    return render(request, 'social/search.html', context)

@login_required
@require_POST
def like_post(request):
    # view for like and unlike posts
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = get_object_or_404(Post, pk=post_id)
        user = request.user

        if user in post.likes.all():
            post.likes.remove(user)
            liked = False
        else:
            post.likes.add(user)
            liked = True

        post_likes_count = post.likes.count()
        response_data = {
            'liked': liked,
            'post_likes_count': post_likes_count
        }
    else:
        response_data = {'error': 'Invalid post_id'}
    return JsonResponse(response_data)

@login_required
@require_POST
def save_post(request):
    # view for save and unsave posts
    post_id = request.POST.get('post_id')
    if post_id is not None:
        post = get_object_or_404(Post, pk=post_id)
        user = request.user
        if user in post.saved_by.all():
            post.saved_by.remove(user)
            saved = False
        else:
            post.saved_by.add(user)
            saved = True
        return JsonResponse({'saved': saved})
    return JsonResponse({'error': 'Invalid Request'})

@login_required
def user_list(request):
    # view for show users list
    users = User.objects.filter(is_active=True)
    return render(request, "user/user_list.html", {"users": users})

@login_required
def user_detail(request, username):
    # view for show user detail
    user = get_object_or_404(User, username=username, is_active=True)
    return render(request, "user/user_detail.html", {"user": user})

@login_required
@require_POST
def user_follow(request):
    user_id = request.POST.get('id')
    if user_id:
        try:
            user = User.objects.get(id=user_id)
            if request.user in user.followers.all():
                Contact.objects.filter(user_from=request.user, user_to=user).delete()
                follow = False
            else:
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                follow = True
            followers_count = user.followers.count()
            following_count = user.following.count()

            return JsonResponse({
                'follow': follow,
                'followers_count': followers_count,
                'following_count': following_count
            })

        except User.DoesNotExist:
            return JsonResponse({'error': 'کاربر یافت نشد.'})

    return JsonResponse({'error': 'درخواست نامعتبر است.'})

social/templates/social/detail.html
{% extends 'parent/base.html' %}
{% block title %}Post Detail{% endblock %}

{% block content %}

    <div class="post" data-post-id="{{ post.id }}">
        <p>{{ post.description|truncatewords:10|linebreaks }}</p>
        <p>در تاریخ {{ post.create }} توسط {{ post.author }} منتشر شد</p>

        <button class="like-button">
            {% if request.user in post.likes.all %}
            	Unlike
            {% else %}
                Like
            {% endif %}
        </button>

        <span class="likes-count">{{ post.likes.count }}</span>
    </div>

    <button class="save-post">
        {% if user in post.saved_by.all %}
            Unsave
        {% else %}
            Save
        {% endif %}
    </button>

    {% for tag in post.tags.all %}
        <a href="{% url 'social:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}

    <h4>پست های مشابه</h4>
    {% for post in similar_post %}
        <a href="{{ post.get_absolute_url }}">{{ post.description }}</a>
    {% empty %}
        <p>پست مشابه وجود ندارد</p>
    {% endfor %}

{% endblock %}

{% block script %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>
        $(document).ready(function() {
            $('.like-button').click(function() {
                var post_id = $(this).closest('.post').data('post-id');
                var button = $(this);

                $.ajax({
                    type: 'POST',
                    url: "{% url 'social:like_post' %}",
                    data: {"post_id": post_id, "csrfmiddlewaretoken": "{{ csrf_token }}"},
                    success: function(data) {
                        if(data.liked) {
                            button.text("Unlike");
                        }
                        else {
                            button.text("Like");
                        }
                        $('.likes-count').text(data.post_likes_count);
                    }
                });
            });
            $('.save-post').click(function (){
                var button = $(this);
                $.ajax({
                    type: "POST",
                    url: "{% url 'social:save_post' %}",
                    data: { "csrfmiddlewaretoken": '{{csrf_token}}', "post_id": {{post.id}} },
                    success: function (data){
                        if (data.saved) {
                            button.text('Unsave')
                        }
                        else {
                            button.text('Save')
                        }
                    }
                })
            })
        })
    </script>

{% endblock %}

social/templates/social/index.html
{% extends 'parent/base.html' %}
{% block title %}Home{% endblock %}

{% block content %}

  <h4>شما با موفقیت وارد شدید</h4>

{% endblock %}

social/templates/social/list.html
{% extends 'parent/base.html' %}
{% block title %}Posts{% endblock %}

{% block content %}

    <div id="post-list">
        {% if tag %}
            <h4>پست های تگ {{ tag.name }}</h4>
        {% endif %}

        {% for post in posts %}
            <a href="{{ post.get_absolute_url }}">{{ post.description|truncatewords:10|linebreaks }}</a>
            <p>در تاریخ {{ post.create }} توسط {{ post.author }} منتشر شد</p>
            {% for tag in post.tags.all %}
                <a href="{% url 'social:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}

            <br>
        {% endfor %}
    </div>

    <button id="load-more">بارگذاری بیشتر</button>

{% endblock %}

{% block script %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function (){
        var page = 2;
        $('#load-more').click(function(){
            $.ajax({
                type: 'GET',
                url: "{% if tag %}{% url 'social:post_list_by_tag' tag.slug %}{% else %}{% url 'social:post_list' %}{% endif %}" + "?page=" + page,
                datatype: 'html',
                success: function(data){
                    $('#post-list').append(data);
                    page += 1;
                }
            });
        });
    });
</script>

{% endblock %}

social/templates/social/list_ajax.html
{% for post in posts %}
    <a href="{{ post.get_absolute_url }}">{{ post.description|truncatewords:10|linebreaks }}</a>
    <p>در تاریخ {{ post.create }} توسط {{ post.author }} منتشر شد</p>
    {% for tag in post.tags.all %}
        <a href="{% url 'social:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
{% endfor %}

social/templates/social/profile.html
{% extends 'parent/base.html' %}
{% load thumbnail %}
{% load static %}
{% block title %}{{ user.username }}{% endblock %}

{% block content %}
    {% with user=request.user %}
        <p>سلام {{ user.get_full_name }} عزیز</p>
        {% if user.photo %}
            <a href="{{ user.photo.url }}">
                <img src="{% thumbnail user.photo 100x100 quality=80 %}">
            </a>
        {% else %}
            <img src="{% static 'images/profile/765-default-avatar.png' %}" style="height: 100px; width: 100px;">
        {% endif %}
    {% endwith %}

    <h4>پست های ذخیره شده</h4>

    <ul>
        {% for post in saved_posts %}
            <a href="{{ post.get_absolute_url }}">
                {{ post.description|truncatewords:10 }}
            </a>
            <p>توسط در تاریخ منتشر شد {{ post.create }}{{ post.author }}</p>
            <br>
            <hr>
        {% endfor %}
    </ul>

{% endblock %}

social/templates/social/search.html
{% extends 'parent/base.html' %}
{% block title %}Search Results{% endblock %}

{% block content %}

    {% if query %}
        <h4>{{ query }} :نتایح برای </h4>
    {% endif %}

    {% for post in results %}
        <a href="{{ post.get_absolute_url }}">{{ post.description|truncatewords:10 }}</a>
    {% empty %}
        <h4>نتیجه ای یافت نشد</h4>
    {% endfor %}

{% endblock %}